name: Run Tests
on: [push, pull_request]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools==57.5.0
          pip install -r requirements.txt
      - name: Run tests with unittest
        run: python -m unittest test/test.py
